/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Interface_GenerateKeyC */

#ifndef _Included_Interface_GenerateKeyC
#define _Included_Interface_GenerateKeyC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Interface_GenerateKeyC
 * Method:    secretKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Interface_GenerateKeyC_secretKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
